### ISSUE TITLE
rest.Error struct and error parsing

### ISSUE THREAD

**Issue by mxpv** [kevinburke/twilio-go#11]
Hey. In current implementation `twilio-go` uses `rest.Error` for twilio errors. So in order to check error code I have to pull one more extra package `github.com/kevinburke/rest`. I would suggest to add `twilio-go` specific Error structure for this and reduce user's dependency list. What do you think?

**Comment by kevinburke** [comment]
Hey! So it might be a little unrealistic but the idea is to have one Error object that's useful for every API that implements the HTTP error spec described here: https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-03. (Also the one used by JSON API).

We depend on kevinburke/rest for the HTTP client, so whether you have to import it explicitly or not, it's still going to get built in to the binary.

If you like, you can override the ErrorParser in the `rest.Client` - see http.go - and marshal into a different type - it's just JSON.
