### ISSUE TITLE
Support for ApplicationSid parameter

### ISSUE THREAD

**Issue by alecha** [kevinburke/twilio-go#14]
Hi, as far as I can see there is not support for the `ApplicationSid` parameter (instead of using the `Url`) when making a call. 

If so, I can create a PR to include it because in our scenario we'd like to configure URLs and status callbacks using an app

Thanks!

**Comment by kevinburke** [comment]
Hi @alecha,

You should be able to do this by using the underlying `Create` primitive - which gets called by MakeCall when making requests.

```go
data := url.Values{}
data.Set("From", from)
data.Set("To", to)
data.Set("ApplicationSid", sid)
// ... anything else you want to set ...
call, err := client.Calls.Create(context.TODO(), data)
```

Does that help?

**Comment by kevinburke** [comment]
For more, see https://godoc.org/pkg/github.com/kevinburke/twilio-go/#hdr-Creating_a_Resource.

**Comment by alecha** [comment]
Thanks @kevinburke , that's the solution that I was using but I was wondering if there was a wrapper, but it works 👍 

Another question: which is the suggested way to pass custom parameters that are used inside TwinML's templates? https://support.twilio.com/hc/en-us/articles/230878368-How-to-use-templates-with-TwiML-Bins

**Comment by kevinburke** [comment]
> which is the suggested way to pass custom parameters that are used inside TwinML's templates?

Ah, yikes, I'm not sure that that's possible the way the client library is set up. 

Here's how `Create` is implemented:

```go
func (c *CallService) Create(ctx context.Context, data url.Values) (*Call, error) {
	call := new(Call)
	err := c.client.CreateResource(ctx, "Calls", data, call)
	return call, err
}
```

That eventually calls `client.MakeRequest`:

```go
func (c *Client) MakeRequest(ctx context.Context, method string, pathPart string, data url.Values, v interface{}) error {
	if !strings.HasPrefix(pathPart, "/"+c.APIVersion) {
		pathPart = c.FullPath(pathPart)
	}
	rb := new(strings.Reader)
	if data != nil && (method == "POST" || method == "PUT") {
		rb = strings.NewReader(data.Encode())
	}
	if method == "GET" && data != nil {
		pathPart = pathPart + "?" + data.Encode()
	}
```

Where basically we put the `url.Values` in the query string if it's a GET, or in the POST/PUT body if it's a POST/PUT. There's no real way to do either.

You could try to see if sending extra fields in the POST body populates them in the TwiML template... alternatively you could fork the library and add an extra parameter to MakeRequest to populate both the query string and the post body.

**Comment by alecha** [comment]
Yes I've checked the source code and I assumed there is no way, I will make a PR 👍

**Comment by kevinburke** [comment]
ok - maybe we should open a new issue to discuss the design a little further because I'm a little hesitant to modify existing API for this use case.

**Comment by alecha** [comment]
Absolutely, I will open it, thanks!

**Comment by alecha** [comment]
We can close this one in the meanwhile
