### ISSUE TITLE
idea: consume api-explorer payloads to generate code

### ISSUE THREAD

**Issue by tmc** [kevinburke/twilio-go#19]

**Comment by kevinburke** [comment]
I've considered this, ultimately there are a few reasons mitigating against it:

- It's difficult to go from automated sources to e.g. recognizing which types can be PhoneNumber types, and you'd need to correlate multiple responses to figure out which ones can be nullable.

- It would require a lot of additional work and the library works pretty well as is now; the incremental cost of supporting new API's is not that high compared to a full rewrite.

- There's a source for code generation that would be helpful (the one Twilio uses to generate client libraries) but I don't have access to that source.

**Comment by tmc** [comment]
example: https://godoc.org/github.com/tmc/twiliogen/twilio#AddressesService

**Comment by kevinburke** [comment]
That's certainly an option, though I'm not sure how pleasant that API would be to work with.
