### ISSUE TITLE
Assumes US by default - should be configurable

### ISSUE THREAD

**Issue by kgolding** [kevinburke/twilio-go#41]
https://github.com/kevinburke/twilio-go/blob/113f30c37433cfcec823220cc8ece2be14619bf0/types.go#L25

Either extend NewPhoneNumber() with a default, or add NewPhoneNumberWithDefault() ?

**Comment by kevinburke** [comment]
I'm pretty sure that the API defaults to US country code if a number does not start with a plus sign...

**Comment by kgolding** [comment]
For me here in the UK the API defaults to a +44.

**Comment by kevinburke** [comment]
Just released as part of 2.1
