### ISSUE TITLE
Panics within function 

### ISSUE THREAD

**Issue by Gillani0** [kevinburke/twilio-go#48]
In the following code:
```  
func GetUsage(ctx context.Context, client *twilio.Client, sim string, start, end time.Time, interval time.Duration) ([]types.Bits, error) {
	if interval <= 0 {
		panic("invalid interval: " + interval.String())
	}
```
you are throwing a panic instead of return an error. It's not a very good practice for a production code.

**Comment by kevinburke** [comment]
Hey this is actually pretty standard for invalid inputs. time.NewTicker will do the same with a negative value, time.In(loc *Location) also panics if loc is nil, time.Date() panics if loc is nil. That's just scanning the `time` package in the standard library, I am sure I can find other examples.

**Comment by kevinburke** [comment]
Thank you for the report, though! Please feel free to keep sending if you find other problems.
