### ISSUE TITLE
Question about exporting Client struct properties

### ISSUE THREAD

**Issue by chartpath** [kevinburke/twilio-go#61]
Hi, thanks for the library!

I am a total Go noob and just ran into my first debugging rabbit hole using this project. The issue ended up being that I was calling `twilioClient.Notify.CreateResource` even though my client had already been created using `twilio.NewNotifyClient()`. Clearly user error, but I got there through auto-completion of the exported things, saw that the Notify client wraps the default one, and could not understand the resulting error (nil pointer dereference).

So just curious, are those properties exported intentionally?

**Comment by kevinburke** [comment]
Hey! Yes... I think the idea is if you wanted to _only_ interact with the Notify API, you could build a client just for that specific resource and avoid the memory usage of the everything client.

Sorry about that. Can you describe what happened a little more, or paste a code snippet? 

I suppose I could add a circular reference - Notify points to itself - but I'm not super happy with that idea either.

**Comment by chartpath** [comment]
So that is actually what I was trying to do, having sensed that it might be exported for that. The offending code was:

```go
// pass nil http client because kevinburke/twilio-go makes one
twilClient := twilio.NewNotifyClient(env.TwilSid, env.TwilTok, nil)
type Res struct {
	Body string `json:"body"`
}
data := url.Values{
	"ToBinding": []string{
		`{"binding_type":"sms", "address":"+5555555555"}`,
	},
	"Body": []string{"hi"},
}
notifRes := &Res{}
twilClient.Notify.CreateResource(context.TODO(), fmt.Sprintf("/Services/%s/Notifications", env.TwilNotifSid), data, notifRes)
fmt.Println(notifRes)
```

The error was:

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1a05ef8]
goroutine 1 [running]:
github.com/kevinburke/twilio-go.(*Client).MakeRequest(0x0, 0x1e78ba0, 0xc000134010, 0x1c54a20, 0x4, 0xc00002b380, 0x3a, 0xc0000a5a90, 0x1b4f7a0, 0x2679660, ...)
        /Users/chris/go/pkg/mod/github.com/kevinburke/twilio-go@v0.0.0-20200630070730-ac4e42b98b94/http.go:484 +0x78
github.com/kevinburke/twilio-go.(*Client).CreateResource(...)
        /Users/chris/go/pkg/mod/github.com/kevinburke/twilio-go@v0.0.0-20200630070730-ac4e42b98b94/http.go:448
github.com/.../api-events/cmd.glob..func1(0x2642880, 0x26785c0, 0x0, 0x0)
        /Users/chris/code/api-events/cmd/server.go:132 +0xd3a
...
exit status 2
```

At first I thought it was my response struct reference, so I learned a bit about pointers and interfaces 😄  Then using a debugger I found out that the Client was actually nil at twilio-go/http.go:448. Which seemed weird because my top-level client was properly created and not nil. Changing the resource call to use `twilClient.CreateResource()` (removing the `.Notify` part) made it work. So that just made me curious why those other client struct properties are exported to external users.

I could see implementing a custom `Notify.CreateResource` method that doesn't require path or service SID arguments. Then calling `twilClient.Notify.CreateResource()` could be a thing. Seems like that is the kind of API that is already implemented by some of the other features, e.g. `client.Recordings.GetPage(context.TODO(), url.Values{})` rather than having to call `client.GetPage()` and pass in more stuff to know it's a Recordings service. I hope I am reading things correctly, thanks!
