### ISSUE TITLE
Getting dependency error 

### ISSUE THREAD

**Issue by slegs** [kevinburke/twilio-go#96]
Have used your library for a while but just in last few days am getting a dependency error on the module

Was trying to revert to a previous version but there doesn't seem to be module versioning

```
github.com/kevinburke/twilio-go@v0.0.0-20220922200631-8f3f155dfe1f requires
github.com/kevinburke/handlers@v0.0.0-20220416175136-cbf86af60bb5: missing go.sum entry; to add it:
	go mod download github.com/kevinburke/handlers

```

**Comment by slegs** [comment]
Closing...looks like something in my environment

**Comment by kevinburke** [comment]
Oh okay! Glad you got it sorted.
